### ISSUE TITLE
com.parasoft.api.rest.client.ParasoftApiFault: The provided user does not have permission to modify this resource.

### ISSUE THREAD

**Issue by rafi-m** [parasoft/soatest-cucumber#1]
i tried a simple step to write a file using cucumber and SoaTest.

my feature File has below steps:

Feature: Integrate parasoft SoaTest with Cucumber

Scenario: BDD Test
Given I am user 12212

below is json step defn.

"stepdefs": [
    {
      "step": "Given",
      "pattern": "^I am user (.*)$",
      "args": 1,
      "actions": [
        "copy:/parabank.cucumber/parabank_stepdefs.tst/Test Suite/Test Steps/Write File"
        
      ]

below is error im getting on console.

cucumber.runtime.CucumberException: The provided user does not have permission to modify this resource.
	at com.parasoft.cucumber.soatest.StepDefinitionLoader.lambda$new$1(StepDefinitionLoader.java:106)
	at cucumber.runtime.java.Java8HookDefinition$1.call(Java8HookDefinition.java:53)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.java.Java8HookDefinition.execute(Java8HookDefinition.java:47)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by benken-parasoft** [comment]
> ParasoftApiFault: The provided user does not have permission to modify this resource

This is a message from a fault that is being returned from the SOAtest server.  If your SOAtest server is configured to authenticate requests against Parasoft CTP then you need to use a credential that permits write access to assets on the SOAtest server.

The [StepDefinitionLoader](https://github.com/parasoft/soatest-cucumber/blob/master/src/main/java/com/parasoft/cucumber/soatest/StepDefinitionLoader.java) from this module sends credentials to the SOAtest server from java system properties "soatest.username" and "soatest.password".  Please set those system properties in the command line or launch configuration you are using to launch JUnit/Cucumber.  Java system properties are set on the command line with '-D', for example: -Dsoatest.user=admin -Dsoatest.password=password

For questions like this, I would encourage you to use the [Parasoft SOAtest forum](https://forums.parasoft.com/categories/soatest) which is monitored by many Parasoft SOAtest users.  [Parasoft Support](https://www.parasoft.com/support) can also help provide a timely response.

**Comment by rafi-m** [comment]
im sorry to ask this here. I use soaTest 9.9. how do we identify if Server is configured to authenticate request against soatest. I have asked the same question on Parasoft SOATest forum too.

**Comment by benken-parasoft** [comment]
Your SOAtest Server is configured to authenticate requests from clients.  We know this because you are getting an error message back from the SOAtest Server indicating that you don't have permission to create or modify test assets.  Authentication is enabled when SOAtest Server is configured to connect to a Parasoft Continuous Testing Platform (CTP) server.  The connection to Parasoft CTP is something that is configured in the preferences on the SOAtest Server.

**Comment by benken-parasoft** [comment]
I see you opened a thread on the forum.  Let's continue there: https://forums.parasoft.com/discussion/3882/bdd-intergration-with-soatest-the-provided-user-does-not-have-permission-to-modify-this-resource
